### ISSUE TITLE
DW and MPM algorism always return -1 value

### ISSUE THREAD

**Issue by dokechin** [peterkhayes/pitchfinder.js#5]
pitchfiner is very nice library.
I made pitchfiner.js example, https://github.com/dokechin/pitchfinder-example
I looked like YIN is going well, but DW and MPM could not 
return frequency value. Always -1 value returning.

**Comment by peterkhayes** [comment]
Thanks for the PRs.  My notification settings have been funny, so I didn't see your requests.  I've merged them now.
